pipeline {
    agent any
    stages {
        stage ('checkout git scm') {
            steps {
                script {
                    checkout scm
                }
            }
        }
        stage ('update docker tag in deplyoment file') {
            steps {
                script {
                    sh "cat ./ecommerce-kubemanifest/deployment.yaml"
                    sh "sed -i 's+rajeshnayak2799/ecommerce.*+rajeshnayak2799/ecommerce:${DOCKERTAG}+g' ./ecommerce-kubemanifest/deployment.yaml"
                    sh "cat ./ecommerce-kubemanifest/deployment.yaml"
                }
            }
        }
        stage ('push changes to GIT') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId:'github-creds', passwordVariable:'GIT_PASSWORD', usernameVariable:'GIT_USERNAME')]) {
                        sh "git config user.email 'jenkins@jenkins.com'"
                        sh "git config user.name 'Jenkins'"
                        sh "git remote set-url origin https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/rajesh-nayak-27/ecommerce.git"
                        sh "git add ./ecommerce-kubemanifest/deployment.yaml"
                        sh "git commit -m 'Update deployment Image to version ${DOCKERTAG}'"
                        sh "git push origin HEAD:master"
                    }
                }
            }
        }
    }
}