piVersion: v1
kind: Service
metadata:
  name: ecommerce
  namespace: ecommerce
  labels:
    app: ecommerce
spec:
  selector:
    app: ecommerce
  type: LoadBalancer
  ports:
    - port: 80
      protocal: TCP
      targetPort: 5000
